name: duoduo_autocheck

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行（北京时间8点）
  workflow_dispatch:     # 允许手动触发

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v4

    - name: 安装Chrome浏览器
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 设置 duoduo_signin.py 可执行权限
      run: chmod +x scripts/duoduo_signin.py

    - name: 确认脚本路径和权限
      run: ls -l scripts/duoduo_signin.py

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests
        
    - name: 运行签到脚本
      timeout-minutes: 10
      run: python scripts/duoduo_signin.py
      env:
        DUODUO_TOKEN: ${{ secrets.DUODUO_TOKEN }}