name: duoduo_autocheck

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行（北京时间8点）
  workflow_dispatch:     # 允许手动触发

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v4

    - name: 安装Chrome浏览器
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 检查当前目录内容
      run: ls -R

    - name: 检查 scripts 目录内容
      run: |
        echo "当前工作目录:"
        pwd
        echo "工作目录内容:"
        ls -R
        echo "scripts 目录内容:"
        ls scripts || echo "scripts 目录不存在"

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager requests
        
    - name: 运行签到脚本
      timeout-minutes: 10
      run: python scripts/duoduo_signin.py
      env:
        DUODUO_TOKEN: ${{ secrets.DUODUO_TOKEN }}