name: duoduo_autocheck

on:
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点运行（北京时间8点）
  workflow_dispatch:     # 允许手动触发

jobs:
  签到任务:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码库
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager
        
    - name: 运行签到脚本
      run: python scripts/duoduo_signin.py
      env:
        DUODUO_TOKEN: ${{ secrets.DUODUO_TOKEN }}
